### ISSUE TITLE
Server error with sacred NeptuneObserver

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ml/neptune-contrib#53]
Everything was working nicely for 2 hours. Then, I started getting:
```WARNING - neptune.internal.channels.channels_values_sender - Failed to send channel value: Server error. Please try again later.```
and later a number of following stacktraces:
```
Exception in thread Thread-26:                                                                                            
Traceback (most recent call last):                                                                                            
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/threading.py", line 917, in _bootstrap_inner                   
    self.run()                                                                                                                         
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/internal/channels/channels_values_sender.py", line 121, in run
    self._process_batch()                                                                                             
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/internal/channels/channels_values_sender.py", line 133, in _process_batch
    self._send_values(self._values_batch)                                 
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/internal/channels/channels_values_sender.py", line 158, in _send_values
    self._experiment._send_channels_values(channels_with_values)                                                                       
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/experiments.py", line 1080, in _send_channels_values
    self._backend.send_channels_values(self, channels_with_values)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/utils.py", line 188, in wrapper               
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 513, in send_channels_values
    channelsValues=input_channels_values                                                         
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/bravado/client.py", line 254, in __call__                       
    request_config=request_config,                                                 
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/bravado/requests_client.py", line 193, in request                           
    self.authenticated_request(sanitized_params),
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/bravado/requests_client.py", line 234, in authenticated_request
    return self.apply_authentication(requests.Request(**request_params))                                                                                  
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/bravado/requests_client.py", line 239, in apply_authentication
    return self.authenticator.apply(request)                                                                                                                 
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/oauth.py", line 87, in apply
    self.auth.refresh_token_if_needed()                                   
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/utils.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/oauth.py", line 51, in refresh_token_if_needed
    self._refresh_token()
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/neptune/oauth.py", line 54, in _refresh_token
    self.session.refresh_token(self.session.auto_refresh_url)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 374, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/home/wojciech/miniconda3/envs/magellan-mbbl/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by pitercl** [comment]
Hi @wjaskowski,

Does this happen repeatedly or was it just this once?
We had a short downtime today and this might be related.

**Comment by wjaskowski** [comment]
This happened in 100% of my experiments, i.e. in the only experiment I executed to try out neptune ;P.

I have been thinking for a moment to think that this is because I am sending much more data then 10k per plot. Is this limit ("Each log type in Neptune (metric, text, image) is limited to 10k data points.") really a hard one?

**Comment by wjaskowski** [comment]
Actually, it happened again:
```WARNING - neptune.internal.channels.channels_values_sender - Failed to send channel value: Server error. Please try a
gain later.
```
(...)
```
WARNING - An error ocurred in the '<neptunecontrib.monitoring.sacred.NeptuneObser
ver object at 0x7f9f52453c18>' observer: Server error. Please try again later.
```
Finally I got bunch of:
```
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 2 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 2 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 4 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 4 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 8 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 8 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 16 seconds.
WARNING - neptune.utils - Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
``` and my process hung up, which is very nasty...

**Comment by pitercl** [comment]
Hi @wjaskowski,

we're investigating this. Thanks for letting us know.

**Comment by lmlima** [comment]
It's happening to me too. In my case, it's not caused by data point limit, since I'm sending just one float per experiment. I guess it's caused by the long time (2 to 10 hours long) running before send or stop the experiment. Some long experiments sometimes work, but in most of then I got the error. Using the same code in shorter experiments I had no issue.

This is what my code is doing:
`neptune.create_experiment(params=params_dict)
(long time processing everything)
neptune.send_metric('some_float', some_float)
neptune.stop()
`

**Comment by wjaskowski** [comment]
My experiments were also long (3-10 hours)

**Comment by pitercl** [comment]
Hi @wjaskowski, @lmlima,

the limit of 10k points per experiment is not strictly enforced at the moment. However, sending large amounts of data in short time puts a strain on our system, which may result in a few timeouts here and there. We'll be working on accommodating more traffic in the coming months.

On the client's side we have a retry mechanism, which tries to send a request up to 10 times with rising intervals in between retries, so actual data loss should be extremely rare.

As for the process hanging up, do you know where exactly it hung up? Sending metrics should be completely asynchronous, but we did have a deadlock in earlier versions of `neptune-client`.

@lmlima are you experiencing the issue with timeouts and hangs or with `MissingTokenError`? Or maybe both?

Which version of `neptune-client` are you using?

**Comment by wjaskowski** [comment]
The hung-up happened at the very end of the experiment. Actually it
happened after one additional error but initially I thought they are
unrelated. So the error was when I was sending the result. I was sending a
tuple which was working fine with SacredObserver but it failed with
NeptuneObserver. Is it possible the hung up was due to that?

**Comment by pitercl** [comment]
Which version of `neptune-client` are you using?

**Comment by lmlima** [comment]
I got those errors:
```W0921 19:19:59.657082 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:04.469121 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:08.974529 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:14.914022 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:19.317052 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:24.743944 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:30.990422 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:34.369477 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:37.953355 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:42.254329 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:45.531176 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:21:02.119803 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 2 seconds.
W0921 19:21:13.139394 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 2 seconds.
W0921 19:21:18.504215 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 4 seconds.
W0921 19:21:51.027226 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 2 seconds.
W0921 19:21:53.319947 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPServiceUnavailable(). Retry in 4 seconds.
W0921 19:21:57.576467 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPServiceUnavailable(). Retry in 8 seconds.
W0921 19:22:05.840517 139922553116416 utils.py:194] Http request to Neptune server failed: HTTPServiceUnavailable(). Retry in 16 seconds.
W0921 19:20:02.611533 139924321855232 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:20:53.619077 139927342827264 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
W0921 19:22:31.413591 139927342827264 channels_values_sender.py:159] Failed to send channel value: Received batch errors sending channels' values to experiment SAN-271. Skipping 7 values.
```
I'm using neptune-client 0.4.5.

**Comment by wjaskowski** [comment]
Oh no! New errors today:
```
WARNING - neptune.utils - Http request to Neptune server failed: ConnectionError(MaxRetryError("HTTPSConn
ectionPool(host='ui.neptune.ml', port=443): Max retries exceeded with url: /auth/realms/neptune/protocol/openid-conne
ct/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f72950c6e48>: Failed
 to establish a new connection: [Errno -2] Name or service not known'))")). Retry in 1 seconds.
```
```
WARNING - neptune.utils - Http request to Neptune server failed: RequestsFutureAdapterConnectionError(). 
Retry in 1 seconds
```
Although maybe those are only warnings and I can ignore them?

**Comment by lmlima** [comment]
After neptune-client update to 0.4.8 I got the following behavior:

> neptune.create_experiment(params=params_dict)

> (while long processing)
> W0924 12:47:20.898727 140276484671232 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:47:52.541266 140274384975616 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:06.090204 140274168755968 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:14.481292 140274168755968 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:15.809282 140274384975616 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:23.268472 140276484671232 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:42.695455 140274384975616 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:49.577561 140274384975616 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:48:53.011846 140276484671232 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 12:49:00.032527 140276484671232 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 2 seconds.
> W0924 14:21:01.688745 140276484671232 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> W0924 14:21:22.373420 140274384975616 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> (end processing)

> neptune.send_metric('some_float', some_float)

> neptune.stop()
> W0924 14:25:26.045459 140276945569152 utils.py:194] Http request to Neptune server failed: HTTPRequestTimeout(). Retry in 1 seconds.
> (process aborted during neptune.stop)

While long precessing phase, the neptune.ml web dashboard shows the experiment as "not responding". But, after the process was aborted, it shows status as "succeeded".

**Comment by pitercl** [comment]
The part about `Name or service not known` means that your code cannot resolve the address `ui.neptune.ml` - probably some network glitch.

The rest of the errors are probably due to our servers being under stress. We'll work on that :)

Btw, even after the experiment is stopped (e.g. after calling `neptune.stop()`), the metric values are being sent if the sending thread was unable to send them earlier. That's why it may appear as if the process hangs after `neptune.stop()`.

**Comment by wjaskowski** [comment]
Sounds good!

**Comment by wjaskowski** [comment]
I am closing this issue since those ServerErrors are only warnings (which was initially misleading) and all the metrics are correctly stored despite the warnings.
